# Generated by Django 5.2.15 on 2026-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccn', models.CharField(max_length=6)),
                ('facility_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('looked_up_at', models.DateTimeField(auto_now_add=True)),
                ('facility_data', models.JSONField()),
                ('manual_inputs', models.JSONField()),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_summary_generated_by', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-looked_up_at'],
            },
        ),
    ]
